### ISSUE TITLE
Bug: Click&Drag gets stuck sometimes

### ISSUE THREAD

**Issue by deanrather** [bensmithett/structurizr-mini#3]
Sometimes while using click+drag to move a diagram around on the screen, it will get "stuck" to the cursor, and continue to move around even after releasing the click.

I haven't found a reliable way to reproduce this issue... it just happens quite often.

Clicking resolves the issue.

Please feel welcome to close this ticket if you've never experienced the issue yourself.

**Comment by deanrather** [comment]
I've figured out repro!

1) goto <https://bensmithett.github.io/structurizr-mini>
2) double-click "Internet Banking System"
3) single-click anywhere on the diagram
**_4) the diagram is now "stuck" to your cursor, as if you were still holding down the mouse!_**
5) single-click again
6) the interactions now behave as expected

I've confirmed I can repro this in the latest versions of Chrome, Firefox, and Edge.

**Comment by bensmithett** [comment]
Thanks for the repro. I'd experienced it but didn't realise it was that consistent.

**Comment by bensmithett** [comment]
@deanrather give https://github.com/bensmithett/structurizr-mini/releases/tag/v1.1.2 a whirl

**Comment by deanrather** [comment]
Works a treat! Thanks so much.
