### ISSUE TITLE
Feature Request: Query param to hide top-bar

### ISSUE THREAD

**Issue by deanrather** [bensmithett/structurizr-mini#4]
I sometimes embed diagrams on confluence pages. eg with the url: `https://mySecureIntranet/diagrams/?diagram=myDiagramName`.

Unfortunately, this shows the top-bar, which is undesirable when embedded in another page.

If we could add another query param, eg `&noTopBar=true` or similar which caused structurizr-mini to render without the top-bar, it would make it nicer when embedding in pages.

**Comment by bensmithett** [comment]
## The plan (feedback welcome)

Support an optional `embed` query param. If `true`, the app should render in "iframe mode" which means:

- No nav bar or spacebar keyboard shortcut for navigating to another diagram ("quick nav")
  -  My assumption (and personal experience) here is that you're generally embedding *one diagram* in some docs inline with some context, not the entire workspace, so nav between docs is unnecessary
- A subtle link in a corner to bust out of iframe mode in a new tab

**Comment by bensmithett** [comment]
`embed=true` is available in 1.2.0, thanks for the idea!
https://github.com/bensmithett/structurizr-mini/releases/tag/v1.2.0
